### ISSUE TITLE
Review of section 6: documentation

### ISSUE THREAD

**Issue by r-owen** [lsst-dm/spie-2018-dm-practices#33]
"alongside our software and services to either the scientific community or future developers and operators"
reads nicely, but I think it would be more accurate as:
"alongside our software and services to the scientific community, developers and future operators"
In other words: "either" isn't needed because some documentation is useful to more than one of the three groups,
and we write documentation for our current developers as well as future developers.

I think the following would be clearer as two sentences, because the relationship between "requirements documents" and "design document" is not clear, so the two subjects don't appear to be directly related: "These flow into Data Management requirements documents for each DM product, and then from each design document, we maintain test specification documents."

Regarding: "Finally, we write test reports that implement the test plans.": does a test report implement a test plan or report on the results of a test run according to the plan? "Report" suggests the latter.

Regarding the "Technical notes" section: please consider using the present tense, like the rest of the documentation section.
e.g. instead of "We recognized that DM team members needed to write..." you could say "DM team members often wish to write...as a means of communication within the project" and "Since...we sought to automate as much" could be "Since...we automate as much"

Consider mentioning our "onboarding" documentation, if only as one of a list of items in the appropriate category.

"An effective way to promote this is through strong documentation of internal processes and policies" does not actually state that we do this, and so somewhat implies that we don't but wish we did. I suggest something along the lines of "We have found that an effective way to promote this..."

The section "User documentation" is interesting. The last paragraph lays out a nice means of designing the structure of the Science Platform documentation, but there is a glaring and ominous omission: it says nothing about how we will get the content written. Do we know? Do we have resources identified (developers? tech writers?) and budgeted? If so it would be reassuring to say so. (I realize the next section is "How we build the docs"; it is very informative but I don't think it is intended to answer the questions I just asked).

"a" -> "an" here: "we use a lsst-texmf48" because LSST is pronounced "ell ess ess tee"; see http://blog.apastyle.org/apastyle/2012/04/using-a-or-an-with-acronyms-and-abbreviations.html

Consider deleting "EUPS-managed" from the following: "Since our EUPS-managed software stacks are composed of many Git repositories". I don't think it adds useful information (though I could be wrong).

Please capitalize "change control board" to match usage later in the same paper. Capitalized Words are a bit clumsier to read, but consistency is useful and I think it is important to indicate in some way that the change control board is an official LSST entity.

**Comment by womullan** [comment]
I have fixed the typos and tense, test report  -- some other text mentioned is gone. I am not adding more content like onboarding at the moment .. did not deal with philosphical question of who writes docs. Though that is everyone's job ...
