### ISSUE TITLE
Review of section 7: Decision Making

### ISSUE THREAD

**Issue by r-owen** [lsst-dm/spie-2018-dm-practices#34]
Regarding: "During the research and development phase of the project, DM used a formal process for approving all changes to the DM system. The SAT consisted of scientists and system architecture representatives and had regular meetings to discuss matters arising"
Please rewrite this. The acryonym "SAT" comes out of nowhere and is never spelled out. Nor is its relationship to "the formal process for approving all changes" really explained, since "discussing matters" isn't the same thing as formally approving things. I'm not even sure what sort of changes are being discussed. Fortunately that becomes clearer in the next paragraph.

"We realized that there were two distinct classes of changes being discussed by the SAT..." I think this should introduce the TCT. We used that for many years to handle the developer-level issues. RFCs are better, but the TCT was a good first step to resolving the issues described.

The RFC section of Section 7:

Consider making this a subsection entitled RFCs

I suggest using present tense for all of this: "RFCs were designed to empower individual developers to propose decisions. Emphasis is placed on the developer being responsible for any fall out from a change"
I realize it's a delicate balance between the history...in 2014 we developed" and "Emphasis is placed".
Also I suggest "fall out" -> "fallout" or, better yet, something more neutral (since an example you cite is to implement a change to the style guide); how about "consequences"?

"Any one can comment" -> "Anyone can comment"

"or flagging the RFC to the Change Control Board for more formal decision making" the CCB is described in the next section so I suggest a forward reference of some kind.

Those quibbles aside, I think the RFC section is oustanding. It presents a lot of good information in a very clear and readable way.

Is it worth discussing RFDs anywhere?

7.1 CCB

This is a run-on sentence; please reword: "The CCB process itself is mediated by a bespoke Drupal web app written early in the life of the project; this can lead to confusion when new people are asked to use the system and we would like to switch to Jira, if only that it would be one less tool to use and we could easily link work tickets to LSST Change Requests (LCRs)."
Also consider deleting "Drupal" as an unnecessary detail.
Regarding "Currently, there is no relationship between the LCR number and the URL": what URL?
I suggest shorting the whole discussion of shortcomings of the current system. Just emphasize that using Jira would allow tighter integrate better with the rest of the project and eliminate the need to learn a different tool.

I suggest spelling out CCB witout capital letters in this: "Inside DM we have our own formal CCB". Please reserve the acronym and/or capitalized version for the LSST-wide body.

**Comment by womullan** [comment]
first part of RFC was removed .. SAT is gone
any one  -> anyone check
forward ref to CCB ok
RFDs .. no space 

CCB part was shortened Drupal history removed 

spell out CCB for DM ok
