### ISSUE TITLE
10 Conclusion

### ISSUE THREAD

**Issue by r-owen** [lsst-dm/spie-2018-dm-practices#35]
The Introduction says "The development team consists of more than 70 people working in six different sites" and the Conclusion says "The LSST Data Management Team consists of more than one hundred people spread across multiple locations". Please use a consistent number. Note that both sentences suggest people, not FTEs, and I think that's a good choice. FTEs are a detail.

Typo: "over the year.s".

I find it a bit odd that you acknowledge the people who have contributed to the *discussions* on tooling and process, but not people who contributed to the actual tooling and processes. Consider broadening the thanks a bit. I realize it's hard to know where to stop.

**Comment by womullan** [comment]
got the typo settled on over 90 in both places - changed ack text
We thank all the people who have contributed to the tooling, processes and discussions  over the years.
