### ISSUE TITLE
Line width

### ISSUE THREAD

**Issue by r-owen** [lsst-dm/spie-2018-dm-practices#38]
In 4.2.1 Coding Standards it says "Secondly, we feel that an 80 character line limit is too short and we continue to use a 110 character limit for code. We did experiment with switching to 80 characters for one package, but did not like the result and this motivated us to retain the current limit. For documentation and comments we would like to adopt an 80 character limit,"

That is not quite correct. We have adopted the numpydoc standard of 75 characters for Python documentation. See https://jira.lsstcorp.org/browse/RFC-107 for our standard and https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#id4
for numpydoc

**Comment by womullan** [comment]
thanks I corrected that
