### ISSUE TITLE
Proofreading

### ISSUE THREAD

**Issue by airnandez** [lsst-dm/spie-2018-dm-practices#40]
This issue contains a set of suggested modifications to correct some typos. It contains a separate comment per suggested correction.

**Comment by airnandez** [comment]
etc --> etc.

Where: [agile.tex:20](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/agile.tex#L20)

**Comment by airnandez** [comment]
LSST Community forum, --> LSST Community forum (without the comma, since it is the end of the phrase)

Where: [community.tex:4](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/community.tex#L4)

**Comment by airnandez** [comment]
Tech Note --> technical note

I would also suggest to add a reference to section "6.1.1 Project documentation"

Where: [confluence.tex:8](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/confluence.tex#L8)

**Comment by airnandez** [comment]
Thi --> This

Where: [doctypes.tex:47](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/doctypes.tex#L47)

**Comment by airnandez** [comment]
Replace "(add reference)" to reference

Where: [docbuilds.tex:35](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/docbuilds.tex#L35)

**Comment by airnandez** [comment]
jenkins --> Jenkins

Where: [pipelinedeploy.tex:10](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/pipelinedeploy.tex#L10)

**Comment by airnandez** [comment]
For consistency, I suggest either to use the same typography for “weekly” and “nightly” as in section 9.1 or just to remove the quotes, since these terms have already being introduced.

Where: [pipelinedeploy.tex:19](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/pipelinedeploy.tex#L19)

**Comment by airnandez** [comment]
Shouldn't it be mentioned here that the reference platform is CentOS 7 as well as g++ 6 and Python 2 and 3? I think that not only the operating system matters in this context but the compiler and interpreter matter as well.

Where: [pipelinedeploy.tex:40](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/pipelinedeploy.tex#L40)

**Comment by airnandez** [comment]
In the phrase:

> eups4.3 “source packages” ...

the reference to the EUPS section makes this look weird.

Where: [pipelinedeploy.tex:53](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/pipelinedeploy.tex#L53)

**Comment by airnandez** [comment]
source based --> source-based

Where: [pipelinedeploy.tex:55](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/pipelinedeploy.tex#L55)

**Comment by airnandez** [comment]
small- scale --> small-scale  (there is a blank after the hyphen)

Where: [qserv.tex:10](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/qserv.tex#L10)

**Comment by airnandez** [comment]
thirty node --> thirty-node

Where: [qserv.tex:16](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/qserv.tex#L16)

**Comment by airnandez** [comment]
Kubernetes ready --> Kubernetes-ready

Where: [jupyterlab.tex:9](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/jupyterlab.tex#L9)

**Comment by airnandez** [comment]
I would suggest at least the first usage of the terms gcloud, kubectl, and awscli in this paragraph to use typewriter font (i.e. `\texttt{xxx}`)

Where: [jupyterlab.tex:29](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/jupyterlab.tex#L29)

**Comment by airnandez** [comment]
kubernetes --> Kubernetes

Where: [jupyterlab.tex:35](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/jupyterlab.tex#L35)

**Comment by airnandez** [comment]
releases --> release

Where: [in2p3.tex:3](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/in2p3.tex#L3)

**Comment by airnandez** [comment]
In

> and the build will be fail if...

I would suggest "and the build will fail if..." or "and the build will be marked as failed if..."


Where: [qserv.tex:10](https://github.com/lsst-dm/spie-2018-dm-practices/blob/dff173689b0aa507c1e312def3dd71d585da9e16/qserv.tex#L10)

**Comment by airnandez** [comment]
That's all I have for now.

**Comment by timj** [comment]
Thanks. I've done most of these and I should remove Python 2 completely because earlier in the paper we say it's gone.
