### ISSUE TITLE
parejkoj's review comments

### ISSUE THREAD

**Issue by parejkoj** [lsst-dm/spie-2018-dm-practices#45]
I discovered the slack channel, which suggested people file issues for comments, so here they are.

* Something wrong with this sentence: 
>	The Primavera5 system outputs standard project metrics on variance and budget which is reasonable for reporting hardware based activities it does track Agile progress well unless there are well defined deliverables.

* Is it worth saying a bit more about why we prefer 110 characters? Largely our longer python/C++ names making `80 - x*4` characters (x-levels of indent) result in bad line breaks. 

* Italicized `n` in this:
> 75 character limit of numpydoc 

* The statement about “no longer waste time…” implies that everyone is committing flake8 compliant code, but that’s just not true. Quite a few people aren’t running linters in their editors. That might warrant a comment, since you’re unlikely to get full flake8 compliance without editor level testing or having travis checks turned on everywhere (which we don’t have yet).

* You say “110 character line limit to maintain consistency with our Python coding standards.” but it was really the other way around: we started with 110 for C++ (which is more verbose in general) and stuck with it for python.

* Thank you for mentioning code coverage. I hope we can get automatic scons-generated coverage reports soon!

* re: EUPS: I believe that UPS came well before SDSS. It was developed by FermiLab for their own things, and adapted for SDSS. If you can’t get any details from Russell or Robert, I can try asking on the SDSS mailing list and/or Nikhil Padmanabhan for a reference.   I did find a github mirror of the UPS repository, that goes back to circa 1997 (The release notes only go back to version 4, which was late 1998): https://github.com/brettviren/fnal-ups

* Also, it may be called Extended Unix Product System now, but the “e” came from its original name: “evilups”. See:
https://github.com/RobertLuptonTheGood/eups/tree/c302e7402e2c4745b3fc7e3e626d57e14ffc82ce

* “by understanding the dependencies” - I think that should be worded “by being told the dependencies”: it’s not an automatic dependency discovery system.
* similarly, the database doesn’t “know” which product version, it is told those things. I’d word it “When a product is installed its location, version, and the versions of its dependencies is stored in a database (currently consisting of files using a bespoke file format), so that a coherent environment can be presented to the user.”

* I think you should at least mention `modules`, which is the much more commonly used software environment management system, and say something about why we’re not using it (history and politics, as far as I know). SDSS switched from eups to modules about three years ago. http://modules.sourceforge.net

* In section 4.4.1, you don’t specifically say what the “fourth type of software” is: you say the first three and the reader has to figure out the fourth from context.

* 4.4.3 you use the phrase “EUPS server” but you haven’t defined what that means. EUPS isn’t a server itself, so I assume you meant “we publish pre-built eups packages to a server and eups can download …”

* "improve our efforts in this regard by starting RFC’s or Confluence discussions" - also mention Community here, as that's a common route (slack discussion->Community post).

* The sentence starting "Previews of URLs..." has no verb.

* Section 5.2 should mention that Community provides very useful searching tools to find previous discussions (i.e. much better than slack).

* "LSST the Docs does not provide is own documentation" - its

* Just a thought: is there a citation for LaTeX that we should cite?

* And the above reminds me that we should cite numpy: "Travis E, Oliphant. A guide to NumPy, USA: Trelgol Publishing, (2006)." (per: https://www.scipy.org/citing.html)

* I don't think we should say "docstrings within our Python code are written in the Numpydoc format" in 6.2.3, because it's far from true right now. Maybe "We are converting docstrings in our Python code to the Numpydoc format, from doxygen, ..."

* Section 7 should mention RFDs as a somewhat infrequently used precursor to filing an RFC.

* With your cite of 49 at the start of section 8, I'd also cite the astropy II paper here too, which discusses their use of CI: https://arxiv.org/abs/1801.02634

* Need to define "DSL".

**Comment by timj** [comment]
Thanks. Regarding the eups commentary, can you please take a look at #42 ? This paper is also meant to be saying where we are going to be around September so I've assumed that things we have started will be mostly true by then.

**Comment by womullan** [comment]
Primavera sentence fixed in #46

**Comment by timj** [comment]
I've tried to deal with these comments in #48 -- some were dealt with previously in #42 and #47. I have added references to numpy and matplotlib. This required some squashing because we have a tight 20 page limit and Latex keeps wanting to push us over to the next page. For that reason I did not cite Latex or mention RFDs (we don't use them much at all).
